version: '2.4'
services:
  node:
    tty: true
    stdin_open: true
    container_name: <TODO__REPOSITORY_NAME_LC>
    env_file:
      - ./.env
    build:
      context: .
      args:
        - NPM_TOKEN
    ports:
      - '<TODO__DEBUG_PORT_NUMBER>:9229'
    user: 'node:node'
    volumes:
      - '.:/home/node/app:rw'
